{% set name = "clearml-agent" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/allegroai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9f5aeb8c4382cfe253a866b18192199dc20920752da1a6407b8a267323413644

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - clearml-agent = clearml_agent.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=18.0,<23.0.0
    - furl >=2.0.0,<2.2.0
    - jsonschema >=2.6.0,<5.0.0
    - pathlib2 >=2.3.0,<2.4.0
    - psutil >=3.4.2,<5.10.0
    - pyparsing >=2.0.3,<3.1.0
    - python-dateutil >=2.4.2,<2.9.0
    - pyjwt >=2.4.0,<2.7.0
    - PyYAML >=3.12,<6.1
    - requests >=2.20.0,<=2.31.0
    - six >=1.13.0,<1.17.0
    - urllib3 >=1.21.1,<1.27.0
    - virtualenv >=16,<21

test:
  imports:
    - clearml_agent
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - clearml-agent --help

about:
  home: https://github.com/allegroai/clearml-agent
  summary: 'ML-Ops made easy. ML-Ops scheduler & orchestration solution'
  description: |
    ClearML Agent - ML-Ops made easy. ML-Ops scheduler & orchestration solution
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://clear.ml/docs/
  dev_url: https://github.com/allegroai/clearml-agent

extra:
  recipe-maintainers:
    - mukhery
